#!/bin/bash

if ! [ $# -eq 1 ]
then
    echo "Usage: `basename $0` [start|restart|stop|status]"
    exit 1
fi

case "$1" in
    start)
        echo "Starting Nginx..."
        sudo service nginx start
        sleep 1
        echo "Starting PHP5..."
        sudo service php5-fpm start
        sleep 1
        echo "Starting PostgreSql..."
        sudo service postgresql start
        sleep 1
    ;;
    stop)
        echo "Stoppting Nginx..."
        sudo service nginx stop
        sleep 1
        echo "Stopping PHP5..."
        sudo service php5-fpm stop
        sleep 1
        echo "Stopping PostgreSql..."
        sudo service postgresql stop
        sleep 1
    ;;
    restart)
        echo "Restarting Nginx..."
        sudo service nginx restart
        sleep 1
        echo "Restarting PHP5..."
        sudo service php5-fpm restart
        sleep 1
        echo "Restarting PostgreSql..."
        sudo service postgresql restart
        sleep 1
    ;;
    status)
        sudo service nginx status
        sudo service php5-fpm status
        sudo service postgresql status
        exit 0
    ;;
    *)
        echo "Usage: `basename $0` [start|restart|stop|status|install]"
    ;;
esac